fix(comment): add comment likes
e-dialect/hinghwa-dict-web pull request #141
Opened 2023-11-27 11:24 UTC by Shxuuer

close #105

2023-11-30 09:49 UTC, FrogDar requested changes

2023-11-30 09:49 UTC, FrogDar commented on src/components/Articles/CommentList.vue
> +                <LikeOutlined style="margin-right: 6px" :style="{color: doLikeHaveMe(item.id) ? '#000' : '#0f0'}"/>{{item.likes}}点赞
我这里显示的时候貌似已点赞并没有成功变色？

2023-11-30 09:50 UTC, FrogDar commented on src/components/Articles/CommentList.vue
> +                <LikeOutlined style="margin-right: 6px" :style="{color: doLikeHaveMe(item.id) ? '#000' : '#0f0'}"/>{{item.likes}}点赞
![image](https://github.com/e-dialect/hinghwa-dict-web/assets/20886330/227611f8-2263-48d3-926d-bebcde26c50c)

2024-03-08 07:51 UTC, lin594 commented
因为用vue3写了，我是不是这里都不需要合并了，等之后再说？ @Shxuuer

2024-04-02 08:13 UTC, lin594 commented
那甚至这个也可以拿起来修复一下

2024-04-16 05:12 UTC, closed without merging