fix: can't comment without login
e-dialect/hinghwa-dict-web pull request #29
Opened 2022-08-07 07:42 UTC by 123daxian

close #18

2022-08-07 07:43 UTC, 123daxian commented
<img width="609" alt="未登录" src="https://user-images.githubusercontent.com/106299221/183280658-a6a5a619-65d9-46f2-a608-0b892be3066e.png">
以上为未登录的界面
<img width="610" alt="登良后" src="https://user-images.githubusercontent.com/106299221/183280676-cf2d3c64-18a6-47d3-88a9-bca886c1d516.png">
以上为登录后的界面

2022-08-08 08:15 UTC, FrogDar requested changes
使用封装过的 hasLogin 来代替 `user.id!=''` 吧
（有封装用封装肯定更好）

2022-08-08 10:44 UTC, 123daxian commented
我需要自己封装吗，还是原代码里已经有封装好的hasLogin了

2022-08-10 16:11 UTC, FrogDar commented
> 我需要自己封装吗，还是原代码里已经有封装好的hasLogin了

已经有封装好的，在那个store里你应该看得到
（这部分内容或许你需要看看 vuex ？ 这也是 vue 的很重要的部分）

2022-08-12 17:01 UTC, FrogDar commented
https://github.com/e-dialect/hinghwa-dict-web/blob/ad1ebaf1fd03ffcfec7f78fb529c9d3dc1b76b87/src/store/index.js#L59-L66

这里已经封装好了呀，你只需要调用这个东西就行……

你可以看看别人是怎么调用的）
同样是 `Vuex` 里的 `user`
https://github.com/e-dialect/hinghwa-dict-web/blob/ad1ebaf1fd03ffcfec7f78fb529c9d3dc1b76b87/src/store/index.js#L78-L80
https://github.com/e-dialect/hinghwa-dict-web/blob/ad1ebaf1fd03ffcfec7f78fb529c9d3dc1b76b87/src/components/Articles/CommentList.vue#L92-L97

2022-08-13 05:58 UTC, 123daxian commented
效果跟之前一样的，我就没有附图，然后我没有用mapGetters来调用，我直接用$store.getters.xxx，这样可以吗

2022-08-13 08:14 UTC, FrogDar commented
> 效果跟之前一样的，我就没有附图，然后我没有用mapGetters来调用，我直接用$store.getters.xxx，这样可以吗

一样的

2022-08-13 08:19 UTC, FrogDar approved these changes

2022-08-13 08:20 UTC, merged