feat(dictionary): optimize dictionary UI
e-dialect/hinghwa-dict-web pull request #82
Opened 2023-01-13 09:11 UTC by 123daxian

1、让拼音对齐展示
2、加了一个折叠框，因为我初次选择A的时候，还有很多可以选择的音序，拼音展示那里还占了很多篇幅，如果可以折叠的话，用户就可以直接看到下面的词语
（如果还有其他的需求也可以提出继续改）

2023-01-13 11:43 UTC, FrogDar requested changes

2023-01-13 11:43 UTC, FrogDar commented on src/services/dictionary.js
> +}
这个东西删掉 没有用

2023-01-13 11:43 UTC, FrogDar commented on src/views/Dictionary/Dictionary.vue
> +        <p style="line-height: 1px">在输入框中输入词语，点击查询即可。</p>
这个换一下说法吧 毕竟是点击点击点击）
或者这里写得少一些 然后增加一个 问号 可以查看帮助？（然后稍微弹出一丢丢帮助页面）

2023-01-13 11:43 UTC, FrogDar commented on src/views/Dictionary/Dictionary.vue
> +        if (this.loading[key] === true) return true
我没有看到哪里有修改这个loading？

2023-01-14 13:44 UTC, FrogDar commented on src/views/Dictionary/Dictionary.vue
>          <a-card :key="list[0]" >
![image](https://user-images.githubusercontent.com/20886330/212474917-6724ce8d-35f9-4552-a526-074dcb5e15c1.png)

加一个 v-if 吧 如果筛选了就只显示这一个拼音相关的

2023-01-14 13:46 UTC, 123daxian commented on src/views/Dictionary/Dictionary.vue
>          <a-card :key="list[0]" >
ok

2023-01-14 16:48 UTC, FrogDar commented
这个查看帮助有点不太好看
可以放在 `音序查词` 旁边 一个 小小的 ？ 图标 这样的

2023-01-14 17:18 UTC, FrogDar approved these changes

2023-01-14 17:19 UTC, merged